### ISSUE TITLE
Provide datasource/feature overrides for scoring

### ISSUE THREAD

**Issue by ragesoss** [wiki-ai/ores#101]
As a follow-on to #100, it would be great to be able to send simply a set of feature scores (for example, the current features of a real revision, but with 10 extra references) and get the model prediction for a revision with those features.

This would let us get a better feel for the behavior of the model, and also let us experiment with using the model to suggest specific interventions that will most improve a page.

**Comment by halfak** [comment]
I just talked to @arlolra about getting this work done.  We discussed the steps that I thought needed to be taken to implement this in ORES.  Here's a quick summary:

Update ores/wsgi/routes/scores.py to handle parameters whose strings match datasource names (e.g. "datasource.revision.text") 
https://github.com/wiki-ai/ores/blob/master/ores/wsgi/routes/scores.py#L109

Update the basic score_processor so that it does not cache scores generated when datasources/features are provided as params. 
https://github.com/wiki-ai/ores/blob/master/ores/score_processors/score_processor.py#L164

We also talked about how we'd encode types in the datasources/features.  I think that JSON will work nicely but will look a bit ugly for strings.  Parameter names will need to be prefixes by "datasource." or "feature." in order to match the datasources and features of interest and that will provide us a ~namespace to make sure we don't overlap with other params (e.g. "precached")

**Comment by halfak** [comment]
OK.  Proposal time!  I'm way overdue here.  

So, recent changes to revscoring (in the jump to `1.0.x`) have made all `revscoring.Feature` and `revscoring.Datasource` identifiable by a unique string.  This would allow us to provide key-value pairs where *key* is the unique string that identifies the `Datasource`/`Feature` and *value* is the value to place in the cache when extracting features and scoring.  Most of the potential values in *value* will be JSON-able (soon, all of them https://github.com/wiki-ai/revscoring/issues/212), so I think we should use JSON encoding for them.

I see two good options for how we could pass these key-value caches to ORES: url-ended params & a flat JSON blob.  To demonstrate the differences between these options, I will demonstrate with a request to get the article quality `wp10` prediction for `rev_id=707605082`, the last edit to the article on [Biology](https://en.wikipedia.org/w/index.php?title=Biology&oldid=707605082).  In this case, we'll hard-code the number of level-2 headers to 10 and set the text to be "bar". 

## Url-encoded params

* GET Request: `/scores/enwiki/wp10/707605082?feature.wikitext.revision.lvl_2_headers=10&datasource.revision.text="bar"`
* POST Request: `/scores/enwiki/wp10/707605082`
  * body: `feature.wikitext.revision.lvl_2_headers=10&datasource.revision.text="bar"`

**Advantages:**

* Common syntax will not surprise anyone.  Uses URL key-value pairs to form key-value pairs for cache.  

**Disadvantages:**

* Double-encoding.  The all values must be JSON encoded and then string encoded.  This will result in some weird looking URLs.  E.g. `"` is encoded as `%22` and `{}` is encoded as `%7B%7D`  However, most browsers do this encoding natively and any code hitting the API won't care. 
* Flat.  It will be difficult to impose hierarchy on this scheme.  But, because we know that values for the cache can only be prefixes with either `feature.` or `datasource.`, this should not result in name clashes.

## JSON blob

* GET Request: `/scores/enwiki/wp10/707605082?caches={"feature.wikitext.revision.lvl_2_headers": 10, "datasource.revision.text": "bar"}`
* POST Request: `/scores/enwiki/wp10/707605082`
  * body: `caches={"feature.wikitext.revision.lvl_2_headers": 10, "datasource.revision.text": "bar"}`

**Advantages:**

* Uniformly double-encoded.  The entire cache itself is encoded in JSON.  This will likely minimize the potential for errors due to double-encoding only subsets of the cache.
* Hierarchical.  A multi-level JSON blob can be passed as a parameter.  We don't need that yet, but we might some day.  Also, by using the `caches` parameter, name clashes are avoided.

**Disadvantages:** 

* Uncommon encoding pattern.  Doesn't take advantage of URL encoding's key-value pairs.  Worse, encoding gets ugly fast.  E.g. the `caches` value in the first URL encodes as `%7B%22feature.wikitext.revision.lvl_2_headers%22%3A%2010%2C%20%22datasource.revision.text%22%3A%20%22bar%22%7D`  This will make it difficult to experiment by passing simple params via the URL.

**Comment by arlolra** [comment]
Think I prefer the JSON blob.

> However, most browsers do this encoding natively and any code hitting the API won't care.

This applies equally in that case. So, the complaint that,

> This will make it difficult to experiment by passing simple params via the URL.

comes down to manually doing JSON formatting, which doesn't seem so bad in the example above.

**Comment by halfak** [comment]
I'm not sure that it does apply equally since there will be substantially less weirdness to encode when using Url-encoded params.  In the case of URL-encoded params, the most complicated encoding will likely be simple quotes whereas in the JSON example, there's spaces, colons, and brackets to deal with.  Still, I'd like to hear from others (@he7d3r & @ragesoss?) about what they think.

In the end, I think that we could actually support both, but I don't want to leap to that conclusion because it will result in more maintenance and testing work.

**Comment by arlolra** [comment]
> in the JSON example, there's spaces, colons, and brackets to deal with

but you said most browsers do that natively ...

Anyways, excited to see this moving forward, in any form.

**Comment by ragesoss** [comment]
Both of those options seem like they'll be pretty simple to use from my perspective. I find JSON APIs a little easier to think about, most of the time, but I also expect to do a lot of url pasting to explore how this kind of data can be used.

**Comment by halfak** [comment]
I had that URL pasting in mind when think of the URL-parsing access method.

E.g. here's a paste of the URL I get for the mail page of zhwiki: https://zh.wikipedia.org/wiki/Wikipedia:%E9%A6%96%E9%A1%B5 

Even when browser handle it natively, you can't assume other formats will.  Like markdown, for example.

**Comment by arlolra** [comment]
True, but you can use the url bar as an encoder.

**Comment by halfak** [comment]
Not once the string is encoded.  I'm struggling to figure out how to get the decoded string from the URL bar.

**Comment by arlolra** [comment]
Just add a space at the end so it switches to "editing mode" and then copy.

**Comment by halfak** [comment]
Interestingly, if I lookup the following URL in Firefox, I can keep editing as-is:

```
https://test.wikipedia.org/wiki/Main_Page?foo={"bar": 5, "baz": 10, "bin": [1, 2, 3, 4, 5]} 
```

But if I try the same in Chrome, the URL will change to the following as soon as I look it up:

```
https://test.wikipedia.org/wiki/Main_Page?foo={%22bar%22:%205,%20%22baz%22:%2010,%20%22bin%22:%20[1,%202,%203,%204,%205]}
```

So, in Firefox, the JSON remains somewhat legible.  But in Chrome, the URL becomes gnarly and hard to edit.  

I'm starting to think that it'll be a good idea to support both.  

**URL editing use-case:**
In the case of URL params, all of the JSON encoded feature values look identical as their string representation.  E.g. `1.1`:*number*, and `true`:*bool*.  No escaped chars necessary.  Only datasources will have complex types and I'm guessing no one is going to do URL editing of those. 

**Machine interaction use-case:**
Within *ores* (and *revscoring*), a *cache* of datasources/features is a single level *dict* with keys that are necessarily strings and values that are almost always trivially JSON-able (excluding rare circumstances that are totally avoidable, see https://github.com/wiki-ai/revscoring/issues/212).  This translates trivially to JSON and back from it.  

----

So I propose a hybrid of the two strategies.  `?cache=<some json>` and `(datasource|feature).<name>=<some json>` will work as expected.  On the back-end, `cache` will take precedence in the case of a naming collision.

**Comment by arlolra** [comment]
Ok, updated the pull.

**Comment by he7d3r** [comment]
I don't have any strong preferences right now.

**Comment by arlolra** [comment]
Close?

**Comment by halfak** [comment]
Close!
