### ISSUE TITLE
RevisionNotFoundErr

### ISSUE THREAD

**Issue by ToAruShiroiNeko** [wiki-ai/ores#17]
Since we should expect for revisions (particularly damaging ones) to end up getting deleted or outright oversighted off for a variety of reasons we should have our code display a more meaningful warning than a traceback. Perhaps something like:

"|Newline|The revision # was not found.|Newline|"

or perhaps it could be a "-" instead of the "."

**Comment by he7d3r** [comment]
Here are some examples where we get `Failed to process <revision.doc>: {'rev_id': ...}`:
https://ores-test.wmflabs.org/scores/ptwiki/?models=reverted&revids=0|1|2

**Comment by halfak** [comment]
This will need to be implemented in the dependency solver.  That's going to be a trick to do in a generalized way.

**Comment by adamwight** [comment]
Here's a variation on the bug: http://ores.wmflabs.org/scores/enwiki/?models=reverted|wp10&revids=672085017

The first revision of an article cannot be checked, because we try to pull parent revision data:
```
 "reverted": {
      "error": {
        "message": "Failed to process <parent_revision.metadata>: RevisionDocumentNotFound",
        "type": "<class 'revscoring.dependencies.errors.DependencyError'>"
      }
    },
```

The correct behavior is to use empty string as the parent revision content, and special case the missing metadata.

**Comment by he7d3r** [comment]
That would be https://github.com/wiki-ai/revscoring/issues/121.

**Comment by halfak** [comment]
Closed in upstream
