### ISSUE TITLE
When scoring a revision, return the version of the model used

### ISSUE THREAD

**Issue by he7d3r** [wiki-ai/ores#24]
Something like this:
```json
{
  "version": 12,
  "scores": {
    "123": {
      "reverted": { ... }
    },
    "456": {
      "reverted": { ... }
    }
}
```
or maybe
```json
{
  "meta": { "version": 12, "timestamp": ..., "etc": ... },
  "scores": {
    "123": {
      "reverted": { ... }
    },
    "456": {
      "reverted": { ... }
    }
}
```
This might be useful when debugging user reports.

**Comment by halfak** [comment]
+1.  This will be critical for secondary caches to make use of too.  For example, the ORES extension for MediaWiki needs to store scores so they can by queried and filtered.  We need to provide a model version *at least* for that extension to do invalidation in a reasonable way.

**Comment by adamwight** [comment]
The MediaWiki extension is not going to rely on this feature.  We'll run the "check model versions" job once an hour and use the most recent values like a global variable, so even in the worst-case scenario the only negative impact of not including the model version is that we've unnecessarily invalidated the previous hour of results.

Still, this seems like an important enhancement, and easy.  It does enable simple caching in any consuming application.

**Comment by halfak** [comment]
I like the "meta" version that Helder proposes, but we'd need to also be able to include the info in multi-model mode. Here's what I imagine:

```
/scores/enwiki?models=damaging|reverted&revids=123456788|123456789&model_info=version|trained|stats
```
```json
{
  "model_info": {
    "damaging": {
      "version": "0.0.4",
      "trained": 1234567890.00,
      "stats": {
         "auc": 0.8937382,
         "accuracy": 0.8892833
      }
    },
    "goodfaith": {
      "version": "0.0.4",
      "trained": 1234567890.00,
      "stats": {
        "auc": 0.9201838,
        "accuracy": 0.756293
      }
    }
  },
  "scores": {
    "123456789": {
      "damaging": {
        "prediction": false, ...
     },
     "goodfaith": {
       "prediction": true, ...
     }
    },
    "123456788": {
      "damaging": {
        "prediction": true, ...
     },
     "goodfaith": {
       "prediction": true, ...
     }
    }
  }
}
```

I think that it would then make sense to include the "scores" sub-field in a simple request.  E.g.: 
```
/scores/enwiki/damaging/123456788
```
```json
{
  "scores": {
    "123456788": {
      "damaging": {
        "prediction": true, ...
     },
    }
  }
}
```

One thing I am struggling with is changing the output format for ORES.  If we do this, I'd like to do it once since we'll ask our users to update their code when we deploy.  It would also be nice if we could have a transition period.  I imagine implement a function that formats a scoring results based on a version number.  E.g. `?format=v2` and that the default would stay "v1" for some transition period.  This function would look like this:

```python
def format_output(scorer_models, scores, model_info, version="v1"):
    """
    Formats a JSON blob of scores.

    :Parameters:
        scorer_models : `set`
            A set of scorer models used in generating the scores.
        scores : `dict`
            A JSONable dictionary of scores by revision ID and model.
        model_info : `set`
            A set of model information keys that should be includes (e.g. "version", 
            "trained" and/or "stats")
        version : `str`
           An output format version to apply.  "v1" excludes any `model_info`. 
           "v2" returns a more complex JSON document format that can 
           contain `model_info`
    """
    ...
```

It would return a JSON blob ready for output.  If version is set to "v1", the response format could not contain the meta information.  If the version is set to "v2", the response format will look like the one above.

**Comment by halfak** [comment]
This was addressed in https://github.com/wiki-ai/ores/pull/121
